// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type StatusPeminjamanEnum string

const (
	StatusPeminjamanEnumMenungguPersetujuan StatusPeminjamanEnum = "Menunggu Persetujuan"
	StatusPeminjamanEnumSedangDipinjam      StatusPeminjamanEnum = "Sedang Dipinjam"
	StatusPeminjamanEnumTidakDipinjam       StatusPeminjamanEnum = "Tidak Dipinjam"
)

func (e *StatusPeminjamanEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StatusPeminjamanEnum(s)
	case string:
		*e = StatusPeminjamanEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for StatusPeminjamanEnum: %T", src)
	}
	return nil
}

type NullStatusPeminjamanEnum struct {
	StatusPeminjamanEnum StatusPeminjamanEnum `json:"status_peminjaman_enum"`
	Valid                bool                 `json:"valid"` // Valid is true if StatusPeminjamanEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatusPeminjamanEnum) Scan(value interface{}) error {
	if value == nil {
		ns.StatusPeminjamanEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StatusPeminjamanEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatusPeminjamanEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StatusPeminjamanEnum), nil
}

type AppKey struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Key  string `json:"key"`
}

type Attachment struct {
	ID         int64          `json:"id"`
	AttachID   string         `json:"attach_id"`
	TaskID     string         `json:"task_id"`
	AttachName sql.NullString `json:"attach_name"`
	AttachUrl  sql.NullString `json:"attach_url"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type AuthToken struct {
	ID                  int64          `json:"id"`
	Name                string         `json:"name"`
	DeviceID            string         `json:"device_id"`
	DeviceType          string         `json:"device_type"`
	Token               string         `json:"token"`
	TokenExpired        time.Time      `json:"token_expired"`
	RefreshToken        string         `json:"refresh_token"`
	RefreshTokenExpired time.Time      `json:"refresh_token_expired"`
	IsLogin             bool           `json:"is_login"`
	UserLogin           sql.NullString `json:"user_login"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
}

type Brand struct {
	ID        int64          `json:"id"`
	BrandID   string         `json:"brand_id"`
	NamaBrand string         `json:"nama_brand"`
	Status    interface{}    `json:"status"`
	CreatedAt time.Time      `json:"created_at"`
	CreatedBy string         `json:"created_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	DeletedBy sql.NullString `json:"deleted_by"`
}

type Client struct {
	ID              int64          `json:"id"`
	ClientID        string         `json:"client_id"`
	ClientName      sql.NullString `json:"client_name"`
	ShipmentAddress sql.NullString `json:"shipment_address"`
	BillingAddress  sql.NullString `json:"billing_address"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       string         `json:"created_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullString `json:"deleted_by"`
}

type Config struct {
	ID          int64          `json:"id"`
	Key         string         `json:"key"`
	Description sql.NullString `json:"description"`
	Value       string         `json:"value"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
}

type DamageHistory struct {
	ID                  int64          `json:"id"`
	DamageHistoryID     string         `json:"damage_history_id"`
	InventarisID        string         `json:"inventaris_id"`
	IDPegawai           string         `json:"id_pegawai"`
	TglRusak            time.Time      `json:"tgl_rusak"`
	TglAwalPerbaikan    time.Time      `json:"tgl_awal_perbaikan"`
	TglSelesaiPerbaikan time.Time      `json:"tgl_selesai_perbaikan"`
	Description         sql.NullString `json:"description"`
	BiayaPerbaikan      int64          `json:"biaya_perbaikan"`
	VendorPerbaikan     int64          `json:"vendor_perbaikan"`
	Status              interface{}    `json:"status"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type DataPegawai struct {
	ID              int64          `json:"id"`
	IDDataPegawai   string         `json:"id_data_pegawai"`
	EmployeeNumber  string         `json:"employee_number"`
	Divisi          sql.NullString `json:"divisi"`
	NamaLengkap     string         `json:"nama_lengkap"`
	TempatLahir     sql.NullString `json:"tempat_lahir"`
	TglLahir        sql.NullTime   `json:"tgl_lahir"`
	JenisKelamin    interface{}    `json:"jenis_kelamin"`
	Kewarganegaraan sql.NullString `json:"kewarganegaraan"`
	Phone           sql.NullString `json:"phone"`
	Mobile          sql.NullString `json:"mobile"`
	Agama           sql.NullString `json:"agama"`
	GolDarah        sql.NullString `json:"gol_darah"`
	Gaji            sql.NullString `json:"gaji"`
	StatusMenikah   sql.NullBool   `json:"status_menikah"`
	NoKtp           sql.NullString `json:"no_ktp"`
	NoNpwp          sql.NullString `json:"no_npwp"`
	Status          interface{}    `json:"status"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       string         `json:"created_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullString `json:"deleted_by"`
}

type DataPelamar struct {
	ID                  int64          `json:"id"`
	IDDataPelamar       string         `json:"id_data_pelamar"`
	IDLowonganPekerjaan string         `json:"id_lowongan_pekerjaan"`
	Email               string         `json:"email"`
	NamaLengkap         string         `json:"nama_lengkap"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	Kewarganegaraan     sql.NullString `json:"kewarganegaraan"`
	Phone               sql.NullString `json:"phone"`
	Mobile              sql.NullString `json:"mobile"`
	Agama               sql.NullString `json:"agama"`
	GolDarah            sql.NullString `json:"gol_darah"`
	StatusMenikah       sql.NullBool   `json:"status_menikah"`
	NoKtp               sql.NullString `json:"no_ktp"`
	NoNpwp              sql.NullString `json:"no_npwp"`
	Status              interface{}    `json:"status"`
	AsalKota            sql.NullString `json:"asal_kota"`
	GajiTerakhir        sql.NullString `json:"gaji_terakhir"`
	HarapanGaji         sql.NullString `json:"harapan_gaji"`
	SedangBekerja       sql.NullString `json:"sedang_bekerja"`
	KetersediaanBekerja sql.NullTime   `json:"ketersediaan_bekerja"`
	SumberInformasi     sql.NullString `json:"sumber_informasi"`
	Alasan              sql.NullString `json:"alasan"`
	KetersediaanInter   sql.NullTime   `json:"ketersediaan_inter"`
	ProfesiKerja        interface{}    `json:"profesi_kerja"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type Inventari struct {
	ID               int64          `json:"id"`
	InventarisID     string         `json:"inventaris_id"`
	BrandID          string         `json:"brand_id"`
	RuanganID        sql.NullString `json:"ruangan_id"`
	UserID           sql.NullString `json:"user_id"`
	KategoriID       string         `json:"kategori_id"`
	VendorID         string         `json:"vendor_id"`
	NamaInventaris   string         `json:"nama_inventaris"`
	Jumlah           int32          `json:"jumlah"`
	TanggalBeli      time.Time      `json:"tanggal_beli"`
	Harga            int64          `json:"harga"`
	Keterangan       sql.NullString `json:"keterangan"`
	OldInventoryCode sql.NullString `json:"old_inventory_code"`
	ImageUrl         sql.NullString `json:"image_url"`
	Status           interface{}    `json:"status"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        string         `json:"created_by"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	DeletedBy        sql.NullString `json:"deleted_by"`
}

type Kantor struct {
	ID         int64          `json:"id"`
	KantorID   string         `json:"kantor_id"`
	NamaKantor string         `json:"nama_kantor"`
	Kota       string         `json:"kota"`
	Alamat     string         `json:"alamat"`
	NomorTelp  string         `json:"nomor_telp"`
	Status     interface{}    `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type Kategori struct {
	ID           int64          `json:"id"`
	KategoriID   string         `json:"kategori_id"`
	NamaKategori string         `json:"nama_kategori"`
	CreatedAt    time.Time      `json:"created_at"`
	CreatedBy    string         `json:"created_by"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	UpdatedBy    sql.NullString `json:"updated_by"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
	DeletedBy    sql.NullString `json:"deleted_by"`
}

type KontakVendor struct {
	ID             int64          `json:"id"`
	KontakVendorID string         `json:"kontak_vendor_id"`
	VendorID       string         `json:"vendor_id"`
	JenisKontak    interface{}    `json:"jenis_kontak"`
	IsiKontak      sql.NullString `json:"isi_kontak"`
	IsPrimary      sql.NullBool   `json:"is_primary"`
	CreatedAt      time.Time      `json:"created_at"`
	CreatedBy      string         `json:"created_by"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	DeletedBy      sql.NullString `json:"deleted_by"`
}

type List struct {
	ID        int64          `json:"id"`
	ListID    string         `json:"list_id"`
	ProjectID string         `json:"project_id"`
	ListName  sql.NullString `json:"list_name"`
	CreatedAt time.Time      `json:"created_at"`
	CreatedBy string         `json:"created_by"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
	UpdatedBy sql.NullString `json:"updated_by"`
	DeletedAt sql.NullTime   `json:"deleted_at"`
	DeletedBy sql.NullString `json:"deleted_by"`
	ListOrder sql.NullInt64  `json:"list_order"`
}

type LowonganPekerjaan struct {
	ID                  int64          `json:"id"`
	IDLowonganPekerjaan string         `json:"id_lowongan_pekerjaan"`
	Posisi              string         `json:"posisi"`
	TglBukaLowongan     time.Time      `json:"tgl_buka_lowongan"`
	TglTutupLowongan    time.Time      `json:"tgl_tutup_lowongan"`
	Kriteria            sql.NullString `json:"kriteria"`
	Deskripsi           sql.NullString `json:"deskripsi"`
	LinkLowongan        sql.NullString `json:"link_lowongan"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type PegawaiAnak struct {
	ID                  int64          `json:"id"`
	IDAnak              string         `json:"id_anak"`
	IDPegawai           string         `json:"id_pegawai"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type PegawaiKeluarga struct {
	ID                 int64          `json:"id"`
	IDKeluarga         string         `json:"id_keluarga"`
	IDPegawai          string         `json:"id_pegawai"`
	NamaIstriSuami     sql.NullString `json:"nama_istri_suami"`
	JenisKelamin       interface{}    `json:"jenis_kelamin"`
	TempatLahir        sql.NullString `json:"tempat_lahir"`
	TglLahir           sql.NullTime   `json:"tgl_lahir"`
	PendidikanTerakhir sql.NullString `json:"pendidikan_terakhir"`
	PekerjaanSkrg      sql.NullString `json:"pekerjaan_skrg"`
	AlamatRumah        sql.NullString `json:"alamat_rumah"`
	CreatedAt          time.Time      `json:"created_at"`
	CreatedBy          string         `json:"created_by"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	DeletedBy          sql.NullString `json:"deleted_by"`
}

type PegawaiPendidikanFormal struct {
	ID              int64           `json:"id"`
	IDPddkFormal    string          `json:"id_pddk_formal"`
	IDPegawai       string          `json:"id_pegawai"`
	JenjangPddk     string          `json:"jenjang_pddk"`
	NamaSekolah     string          `json:"nama_sekolah"`
	JurusanFakultas sql.NullString  `json:"jurusan_fakultas"`
	Kota            sql.NullString  `json:"kota"`
	TglLulus        sql.NullTime    `json:"tgl_lulus"`
	Ipk             sql.NullFloat64 `json:"ipk"`
	CreatedAt       time.Time       `json:"created_at"`
	CreatedBy       string          `json:"created_by"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	UpdatedBy       sql.NullString  `json:"updated_by"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	DeletedBy       sql.NullString  `json:"deleted_by"`
}

type PegawaiPendidikanNonFormal struct {
	ID              int64          `json:"id"`
	IDPddkNonFormal string         `json:"id_pddk_non_formal"`
	IDPegawai       string         `json:"id_pegawai"`
	Institusi       string         `json:"institusi"`
	JenisPendidikan string         `json:"jenis_pendidikan"`
	Kota            sql.NullString `json:"kota"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       string         `json:"created_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullString `json:"deleted_by"`
}

type PegawaiPenguasaanBahasa struct {
	ID         int64          `json:"id"`
	IDBahasa   string         `json:"id_bahasa"`
	IDPegawai  string         `json:"id_pegawai"`
	Bahasa     string         `json:"bahasa"`
	Lisan      sql.NullString `json:"lisan"`
	Tulisan    sql.NullString `json:"tulisan"`
	Keterangan sql.NullString `json:"keterangan"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type PegawaiSaudaraKandung struct {
	ID                  int64          `json:"id"`
	IDSaudara           string         `json:"id_saudara"`
	IDPegawai           string         `json:"id_pegawai"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type PelamarAnak struct {
	ID                  int64          `json:"id"`
	IDAnak              string         `json:"id_anak"`
	IDPelamar           string         `json:"id_pelamar"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type PelamarKeluarga struct {
	ID                 int64          `json:"id"`
	IDKeluarga         string         `json:"id_keluarga"`
	IDPelamar          string         `json:"id_pelamar"`
	NamaIstriSuami     sql.NullString `json:"nama_istri_suami"`
	JenisKelamin       interface{}    `json:"jenis_kelamin"`
	TempatLahir        sql.NullString `json:"tempat_lahir"`
	TglLahir           sql.NullTime   `json:"tgl_lahir"`
	PendidikanTerakhir sql.NullString `json:"pendidikan_terakhir"`
	PekerjaanSkrg      sql.NullString `json:"pekerjaan_skrg"`
	AlamatRumah        sql.NullString `json:"alamat_rumah"`
	CreatedAt          time.Time      `json:"created_at"`
	CreatedBy          string         `json:"created_by"`
	UpdatedAt          sql.NullTime   `json:"updated_at"`
	UpdatedBy          sql.NullString `json:"updated_by"`
	DeletedAt          sql.NullTime   `json:"deleted_at"`
	DeletedBy          sql.NullString `json:"deleted_by"`
}

type PelamarPendidikanFormal struct {
	ID              int64           `json:"id"`
	IDPddkFormal    string          `json:"id_pddk_formal"`
	IDPelamar       string          `json:"id_pelamar"`
	JenjangPddk     string          `json:"jenjang_pddk"`
	NamaSekolah     string          `json:"nama_sekolah"`
	JurusanFakultas sql.NullString  `json:"jurusan_fakultas"`
	Kota            sql.NullString  `json:"kota"`
	TglLulus        sql.NullTime    `json:"tgl_lulus"`
	Ipk             sql.NullFloat64 `json:"ipk"`
	CreatedAt       time.Time       `json:"created_at"`
	CreatedBy       string          `json:"created_by"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	UpdatedBy       sql.NullString  `json:"updated_by"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	DeletedBy       sql.NullString  `json:"deleted_by"`
}

type PelamarPendidikanNonFormal struct {
	ID              int64          `json:"id"`
	IDPddkNonFormal string         `json:"id_pddk_non_formal"`
	IDPelamar       string         `json:"id_pelamar"`
	Institusi       string         `json:"institusi"`
	JenisPendidikan string         `json:"jenis_pendidikan"`
	Kota            string         `json:"kota"`
	TglLulus        sql.NullTime   `json:"tgl_lulus"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       string         `json:"created_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullString `json:"deleted_by"`
}

type PelamarPengalamanKerja struct {
	ID                int64          `json:"id"`
	IDPengalamanKerja string         `json:"id_pengalaman_kerja"`
	IDPelamar         string         `json:"id_pelamar"`
	NamaPerusahaan    string         `json:"nama_perusahaan"`
	Periode           sql.NullString `json:"periode"`
	Jabatan           sql.NullString `json:"jabatan"`
	Gaji              sql.NullString `json:"gaji"`
	AlasanPindah      sql.NullString `json:"alasan_pindah"`
	CreatedAt         time.Time      `json:"created_at"`
	CreatedBy         string         `json:"created_by"`
	UpdatedAt         sql.NullTime   `json:"updated_at"`
	UpdatedBy         sql.NullString `json:"updated_by"`
	DeletedAt         sql.NullTime   `json:"deleted_at"`
	DeletedBy         sql.NullString `json:"deleted_by"`
}

type PelamarPenguasaanBahasa struct {
	ID         int64          `json:"id"`
	IDBahasa   string         `json:"id_bahasa"`
	IDPelamar  string         `json:"id_pelamar"`
	Bahasa     string         `json:"bahasa"`
	Lisan      sql.NullString `json:"lisan"`
	Tulisan    sql.NullString `json:"tulisan"`
	Keterangan sql.NullString `json:"keterangan"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}

type PelamarReferensi struct {
	ID               int64          `json:"id"`
	IDReferensi      string         `json:"id_referensi"`
	IDPelamar        string         `json:"id_pelamar"`
	Nama             string         `json:"nama"`
	NamaPerusahaan   sql.NullString `json:"nama_perusahaan"`
	Jabatan          sql.NullString `json:"jabatan"`
	NoTelpPerusahaan sql.NullString `json:"no_telp_perusahaan"`
	CreatedAt        time.Time      `json:"created_at"`
	CreatedBy        string         `json:"created_by"`
	UpdatedAt        sql.NullTime   `json:"updated_at"`
	UpdatedBy        sql.NullString `json:"updated_by"`
	DeletedAt        sql.NullTime   `json:"deleted_at"`
	DeletedBy        sql.NullString `json:"deleted_by"`
}

type PelamarSaudaraKandung struct {
	ID                  int64          `json:"id"`
	IDSaudara           string         `json:"id_saudara"`
	IDPelamar           string         `json:"id_pelamar"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	CreatedAt           time.Time      `json:"created_at"`
	CreatedBy           string         `json:"created_by"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	DeletedBy           sql.NullString `json:"deleted_by"`
}

type Peminjaman struct {
	ID               int64                `json:"id"`
	UserID           string               `json:"user_id"`
	PeminjamanID     string               `json:"peminjaman_id"`
	InventarisID     string               `json:"inventaris_id"`
	TglPinjam        time.Time            `json:"tgl_pinjam"`
	TglKembali       time.Time            `json:"tgl_kembali"`
	StatusPeminjaman StatusPeminjamanEnum `json:"status_peminjaman"`
	Notes            sql.NullString       `json:"notes"`
	CreatedAt        time.Time            `json:"created_at"`
	CreatedBy        string               `json:"created_by"`
	UpdatedAt        sql.NullTime         `json:"updated_at"`
	UpdatedBy        sql.NullString       `json:"updated_by"`
	DeletedAt        sql.NullTime         `json:"deleted_at"`
	DeletedBy        sql.NullString       `json:"deleted_by"`
}

type Project struct {
	ID              int64          `json:"id"`
	ProjectID       string         `json:"project_id"`
	ClientID        string         `json:"client_id"`
	ProjectName     sql.NullString `json:"project_name"`
	ProjectDesc     sql.NullString `json:"project_desc"`
	ProjectStatus   interface{}    `json:"project_status"`
	ProjectPriority sql.NullString `json:"project_priority"`
	ProjectColor    sql.NullString `json:"project_color"`
	StartDate       sql.NullTime   `json:"start_date"`
	DueDate         sql.NullTime   `json:"due_date"`
	CreatedAt       time.Time      `json:"created_at"`
	CreatedBy       string         `json:"created_by"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	UpdatedBy       sql.NullString `json:"updated_by"`
	DeletedAt       sql.NullTime   `json:"deleted_at"`
	DeletedBy       sql.NullString `json:"deleted_by"`
}

type ProjectMember struct {
	ID            int64       `json:"id"`
	ProjectMembID string      `json:"project_memb_id"`
	IDDataPegawai string      `json:"id_data_pegawai"`
	ProjectID     string      `json:"project_id"`
	ProjectRole   interface{} `json:"project_role"`
}

type Ruangan struct {
	ID          int64          `json:"id"`
	RuanganID   string         `json:"ruangan_id"`
	KantorID    string         `json:"kantor_id"`
	NamaRuangan string         `json:"nama_ruangan"`
	Lantai      sql.NullInt32  `json:"lantai"`
	Status      interface{}    `json:"status"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   string         `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullString `json:"deleted_by"`
}

type Task struct {
	ID           int64           `json:"id"`
	TaskID       string          `json:"task_id"`
	ListID       string          `json:"list_id"`
	TaskName     sql.NullString  `json:"task_name"`
	TaskType     interface{}     `json:"task_type"`
	TaskPriority interface{}     `json:"task_priority"`
	TaskSize     interface{}     `json:"task_size"`
	TaskStatus   interface{}     `json:"task_status"`
	TaskColor    sql.NullString  `json:"task_color"`
	StartDate    sql.NullTime    `json:"start_date"`
	DueDate      sql.NullTime    `json:"due_date"`
	CreatedAt    time.Time       `json:"created_at"`
	CreatedBy    string          `json:"created_by"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	UpdatedBy    sql.NullString  `json:"updated_by"`
	DeletedAt    sql.NullTime    `json:"deleted_at"`
	DeletedBy    sql.NullString  `json:"deleted_by"`
	TaskOrder    sql.NullFloat64 `json:"task_order"`
}

type TaskMember struct {
	ID            int64  `json:"id"`
	TaskMembID    string `json:"task_memb_id"`
	ProjectMembID string `json:"project_memb_id"`
	TaskID        string `json:"task_id"`
}

type UsageHistory struct {
	ID             int64          `json:"id"`
	UsageHistoryID string         `json:"usage_history_id"`
	InventarisID   string         `json:"inventaris_id"`
	OldRoomID      string         `json:"old_room_id"`
	NewRoomID      string         `json:"new_room_id"`
	OldUserID      string         `json:"old_user_id"`
	NewUserID      string         `json:"new_user_id"`
	MovedAt        sql.NullTime   `json:"moved_at"`
	CreatedAt      time.Time      `json:"created_at"`
	CreatedBy      string         `json:"created_by"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
	UpdatedBy      sql.NullString `json:"updated_by"`
	DeletedAt      sql.NullTime   `json:"deleted_at"`
	DeletedBy      sql.NullString `json:"deleted_by"`
}

type UserBackoffice struct {
	ID                     int64          `json:"id"`
	Guid                   string         `json:"guid"`
	Name                   sql.NullString `json:"name"`
	ProfilePictureImageUrl sql.NullString `json:"profile_picture_image_url"`
	Phone                  string         `json:"phone"`
	Email                  string         `json:"email"`
	RoleID                 int32          `json:"role_id"`
	Password               string         `json:"password"`
	Salt                   string         `json:"salt"`
	IsActive               sql.NullBool   `json:"is_active"`
	CreatedAt              time.Time      `json:"created_at"`
	CreatedBy              string         `json:"created_by"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	UpdatedBy              sql.NullString `json:"updated_by"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	DeletedBy              sql.NullString `json:"deleted_by"`
	LastLogin              sql.NullTime   `json:"last_login"`
	IDPegawai              sql.NullString `json:"id_pegawai"`
}

type UserBackofficeRole struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Access      sql.NullString `json:"access"`
	IsAllAccess sql.NullBool   `json:"is_all_access"`
	Level       sql.NullString `json:"level"`
	CreatedAt   time.Time      `json:"created_at"`
	CreatedBy   string         `json:"created_by"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UpdatedBy   sql.NullString `json:"updated_by"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	DeletedBy   sql.NullString `json:"deleted_by"`
}

type UserHandheld struct {
	ID                     int64          `json:"id"`
	Guid                   string         `json:"guid"`
	Name                   string         `json:"name"`
	ProfilePictureImageUrl sql.NullString `json:"profile_picture_image_url"`
	Phone                  sql.NullString `json:"phone"`
	Email                  string         `json:"email"`
	Gender                 string         `json:"gender"`
	Address                sql.NullString `json:"address"`
	Salt                   string         `json:"salt"`
	Password               string         `json:"password"`
	IsActive               sql.NullBool   `json:"is_active"`
	FcmToken               sql.NullString `json:"fcm_token"`
	CreatedAt              time.Time      `json:"created_at"`
	UpdatedAt              sql.NullTime   `json:"updated_at"`
	DeletedAt              sql.NullTime   `json:"deleted_at"`
	LastLogin              sql.NullTime   `json:"last_login"`
}

type Vendor struct {
	ID         int64          `json:"id"`
	VendorID   string         `json:"vendor_id"`
	NamaVendor string         `json:"nama_vendor"`
	Alamat     string         `json:"alamat"`
	Status     interface{}    `json:"status"`
	CreatedAt  time.Time      `json:"created_at"`
	CreatedBy  string         `json:"created_by"`
	UpdatedAt  sql.NullTime   `json:"updated_at"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	DeletedAt  sql.NullTime   `json:"deleted_at"`
	DeletedBy  sql.NullString `json:"deleted_by"`
}
