// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pegawai_anak.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPegawaiAnak = `-- name: CreatePegawaiAnak :one
INSERT INTO pegawai_anak (
    id_anak, id_pegawai, nama, jenis_kelamin, tempat_lahir,
    tgl_lahir, pendidikan_pekerjaan, created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    (now() at time zone 'UTC')::TIMESTAMP, $8
) RETURNING id, id_anak, id_pegawai, nama, jenis_kelamin, tempat_lahir, tgl_lahir, pendidikan_pekerjaan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreatePegawaiAnakParams struct {
	IDAnak              string         `json:"id_anak"`
	IDPegawai           string         `json:"id_pegawai"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	CreatedBy           string         `json:"created_by"`
}

func (q *Queries) CreatePegawaiAnak(ctx context.Context, arg CreatePegawaiAnakParams) (PegawaiAnak, error) {
	row := q.db.QueryRowContext(ctx, createPegawaiAnak,
		arg.IDAnak,
		arg.IDPegawai,
		arg.Nama,
		arg.JenisKelamin,
		arg.TempatLahir,
		arg.TglLahir,
		arg.PendidikanPekerjaan,
		arg.CreatedBy,
	)
	var i PegawaiAnak
	err := row.Scan(
		&i.ID,
		&i.IDAnak,
		&i.IDPegawai,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.TglLahir,
		&i.PendidikanPekerjaan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPegawaiAnakByID = `-- name: GetPegawaiAnakByID :one
SELECT id, id_anak, id_pegawai, nama, jenis_kelamin, tempat_lahir, tgl_lahir, pendidikan_pekerjaan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pegawai_anak
WHERE id_anak = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPegawaiAnakByID(ctx context.Context, idAnak string) (PegawaiAnak, error) {
	row := q.db.QueryRowContext(ctx, getPegawaiAnakByID, idAnak)
	var i PegawaiAnak
	err := row.Scan(
		&i.ID,
		&i.IDAnak,
		&i.IDPegawai,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.TglLahir,
		&i.PendidikanPekerjaan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPegawaiAnak = `-- name: ListPegawaiAnak :many
SELECT id, id_anak, id_pegawai, nama, jenis_kelamin, tempat_lahir, tgl_lahir, pendidikan_pekerjaan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pegawai_anak
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPegawaiAnak(ctx context.Context) ([]PegawaiAnak, error) {
	rows, err := q.db.QueryContext(ctx, listPegawaiAnak)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PegawaiAnak
	for rows.Next() {
		var i PegawaiAnak
		if err := rows.Scan(
			&i.ID,
			&i.IDAnak,
			&i.IDPegawai,
			&i.Nama,
			&i.JenisKelamin,
			&i.TempatLahir,
			&i.TglLahir,
			&i.PendidikanPekerjaan,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePegawaiAnak = `-- name: RestorePegawaiAnak :exec
UPDATE pegawai_anak
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id_anak = $1
`

func (q *Queries) RestorePegawaiAnak(ctx context.Context, idAnak string) error {
	_, err := q.db.ExecContext(ctx, restorePegawaiAnak, idAnak)
	return err
}

const softDeletePegawaiAnak = `-- name: SoftDeletePegawaiAnak :exec
UPDATE pegawai_anak
SET
    deleted_at = (now() at time zone 'UTC')::TIMESTAMP,
    deleted_by = $1
WHERE id_anak = $2
  AND deleted_at IS NULL
`

type SoftDeletePegawaiAnakParams struct {
	DeletedBy sql.NullString `json:"deleted_by"`
	IDAnak    string         `json:"id_anak"`
}

func (q *Queries) SoftDeletePegawaiAnak(ctx context.Context, arg SoftDeletePegawaiAnakParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePegawaiAnak, arg.DeletedBy, arg.IDAnak)
	return err
}

const updatePegawaiAnak = `-- name: UpdatePegawaiAnak :one
UPDATE pegawai_anak
SET
    nama = $1,
    jenis_kelamin = $2,
    tempat_lahir = $3,
    tgl_lahir = $4,
    pendidikan_pekerjaan = $5,
    updated_at = (now() at time zone 'UTC')::TIMESTAMP,
    updated_by = $6
WHERE id_anak = $7
  AND deleted_at IS NULL
    RETURNING id, id_anak, id_pegawai, nama, jenis_kelamin, tempat_lahir, tgl_lahir, pendidikan_pekerjaan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdatePegawaiAnakParams struct {
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	IDAnak              string         `json:"id_anak"`
}

func (q *Queries) UpdatePegawaiAnak(ctx context.Context, arg UpdatePegawaiAnakParams) (PegawaiAnak, error) {
	row := q.db.QueryRowContext(ctx, updatePegawaiAnak,
		arg.Nama,
		arg.JenisKelamin,
		arg.TempatLahir,
		arg.TglLahir,
		arg.PendidikanPekerjaan,
		arg.UpdatedBy,
		arg.IDAnak,
	)
	var i PegawaiAnak
	err := row.Scan(
		&i.ID,
		&i.IDAnak,
		&i.IDPegawai,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.TglLahir,
		&i.PendidikanPekerjaan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
