// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pelamar_penguasaan_bahasa.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPelamarPenguasaanBahasa = `-- name: CreatePelamarPenguasaanBahasa :one
INSERT INTO pelamar_penguasaan_bahasa (
    id_bahasa, id_pelamar, bahasa, lisan, tulisan, keterangan,
    created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    (now() at time zone 'UTC')::TIMESTAMP, $7
) RETURNING id, id_bahasa, id_pelamar, bahasa, lisan, tulisan, keterangan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreatePelamarPenguasaanBahasaParams struct {
	IDBahasa   string         `json:"id_bahasa"`
	IDPelamar  string         `json:"id_pelamar"`
	Bahasa     string         `json:"bahasa"`
	Lisan      sql.NullString `json:"lisan"`
	Tulisan    sql.NullString `json:"tulisan"`
	Keterangan sql.NullString `json:"keterangan"`
	CreatedBy  string         `json:"created_by"`
}

func (q *Queries) CreatePelamarPenguasaanBahasa(ctx context.Context, arg CreatePelamarPenguasaanBahasaParams) (PelamarPenguasaanBahasa, error) {
	row := q.db.QueryRowContext(ctx, createPelamarPenguasaanBahasa,
		arg.IDBahasa,
		arg.IDPelamar,
		arg.Bahasa,
		arg.Lisan,
		arg.Tulisan,
		arg.Keterangan,
		arg.CreatedBy,
	)
	var i PelamarPenguasaanBahasa
	err := row.Scan(
		&i.ID,
		&i.IDBahasa,
		&i.IDPelamar,
		&i.Bahasa,
		&i.Lisan,
		&i.Tulisan,
		&i.Keterangan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPelamarPenguasaanBahasaByID = `-- name: GetPelamarPenguasaanBahasaByID :one
SELECT id, id_bahasa, id_pelamar, bahasa, lisan, tulisan, keterangan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_penguasaan_bahasa
WHERE id_bahasa = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPelamarPenguasaanBahasaByID(ctx context.Context, idBahasa string) (PelamarPenguasaanBahasa, error) {
	row := q.db.QueryRowContext(ctx, getPelamarPenguasaanBahasaByID, idBahasa)
	var i PelamarPenguasaanBahasa
	err := row.Scan(
		&i.ID,
		&i.IDBahasa,
		&i.IDPelamar,
		&i.Bahasa,
		&i.Lisan,
		&i.Tulisan,
		&i.Keterangan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPelamarPenguasaanBahasa = `-- name: ListPelamarPenguasaanBahasa :many
SELECT id, id_bahasa, id_pelamar, bahasa, lisan, tulisan, keterangan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_penguasaan_bahasa
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPelamarPenguasaanBahasa(ctx context.Context) ([]PelamarPenguasaanBahasa, error) {
	rows, err := q.db.QueryContext(ctx, listPelamarPenguasaanBahasa)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PelamarPenguasaanBahasa
	for rows.Next() {
		var i PelamarPenguasaanBahasa
		if err := rows.Scan(
			&i.ID,
			&i.IDBahasa,
			&i.IDPelamar,
			&i.Bahasa,
			&i.Lisan,
			&i.Tulisan,
			&i.Keterangan,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePelamarPenguasaanBahasa = `-- name: RestorePelamarPenguasaanBahasa :exec
UPDATE pelamar_penguasaan_bahasa
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id_bahasa = $1
`

func (q *Queries) RestorePelamarPenguasaanBahasa(ctx context.Context, idBahasa string) error {
	_, err := q.db.ExecContext(ctx, restorePelamarPenguasaanBahasa, idBahasa)
	return err
}

const softDeletePelamarPenguasaanBahasa = `-- name: SoftDeletePelamarPenguasaanBahasa :exec
UPDATE pelamar_penguasaan_bahasa
SET
    deleted_at = (now() at time zone 'UTC')::TIMESTAMP,
    deleted_by = $1
WHERE id_bahasa = $2
  AND deleted_at IS NULL
`

type SoftDeletePelamarPenguasaanBahasaParams struct {
	DeletedBy sql.NullString `json:"deleted_by"`
	IDBahasa  string         `json:"id_bahasa"`
}

func (q *Queries) SoftDeletePelamarPenguasaanBahasa(ctx context.Context, arg SoftDeletePelamarPenguasaanBahasaParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePelamarPenguasaanBahasa, arg.DeletedBy, arg.IDBahasa)
	return err
}

const updatePelamarPenguasaanBahasa = `-- name: UpdatePelamarPenguasaanBahasa :one
UPDATE pelamar_penguasaan_bahasa
SET
    bahasa = $1,
    lisan = $2,
    tulisan = $3,
    keterangan = $4,
    updated_at = (now() at time zone 'UTC')::TIMESTAMP,
    updated_by = $5
WHERE id_bahasa = $6
  AND deleted_at IS NULL
    RETURNING id, id_bahasa, id_pelamar, bahasa, lisan, tulisan, keterangan, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdatePelamarPenguasaanBahasaParams struct {
	Bahasa     string         `json:"bahasa"`
	Lisan      sql.NullString `json:"lisan"`
	Tulisan    sql.NullString `json:"tulisan"`
	Keterangan sql.NullString `json:"keterangan"`
	UpdatedBy  sql.NullString `json:"updated_by"`
	IDBahasa   string         `json:"id_bahasa"`
}

func (q *Queries) UpdatePelamarPenguasaanBahasa(ctx context.Context, arg UpdatePelamarPenguasaanBahasaParams) (PelamarPenguasaanBahasa, error) {
	row := q.db.QueryRowContext(ctx, updatePelamarPenguasaanBahasa,
		arg.Bahasa,
		arg.Lisan,
		arg.Tulisan,
		arg.Keterangan,
		arg.UpdatedBy,
		arg.IDBahasa,
	)
	var i PelamarPenguasaanBahasa
	err := row.Scan(
		&i.ID,
		&i.IDBahasa,
		&i.IDPelamar,
		&i.Bahasa,
		&i.Lisan,
		&i.Tulisan,
		&i.Keterangan,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
