// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pelamar_saudara_kandung.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPelamarSaudaraKandung = `-- name: CreatePelamarSaudaraKandung :one
INSERT INTO pelamar_saudara_kandung (
    id_saudara, id_pelamar, nama, jenis_kelamin, tempat_lahir,
    pendidikan_pekerjaan, tgl_lahir, created_at, created_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, NOW(), $8
) RETURNING id, id_saudara, id_pelamar, nama, jenis_kelamin, tempat_lahir, pendidikan_pekerjaan, tgl_lahir, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreatePelamarSaudaraKandungParams struct {
	IDSaudara           string         `json:"id_saudara"`
	IDPelamar           string         `json:"id_pelamar"`
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	CreatedBy           string         `json:"created_by"`
}

func (q *Queries) CreatePelamarSaudaraKandung(ctx context.Context, arg CreatePelamarSaudaraKandungParams) (PelamarSaudaraKandung, error) {
	row := q.db.QueryRowContext(ctx, createPelamarSaudaraKandung,
		arg.IDSaudara,
		arg.IDPelamar,
		arg.Nama,
		arg.JenisKelamin,
		arg.TempatLahir,
		arg.PendidikanPekerjaan,
		arg.TglLahir,
		arg.CreatedBy,
	)
	var i PelamarSaudaraKandung
	err := row.Scan(
		&i.ID,
		&i.IDSaudara,
		&i.IDPelamar,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.PendidikanPekerjaan,
		&i.TglLahir,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPelamarSaudaraKandungByID = `-- name: GetPelamarSaudaraKandungByID :one
SELECT id, id_saudara, id_pelamar, nama, jenis_kelamin, tempat_lahir, pendidikan_pekerjaan, tgl_lahir, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_saudara_kandung
WHERE id_saudara = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPelamarSaudaraKandungByID(ctx context.Context, idSaudara string) (PelamarSaudaraKandung, error) {
	row := q.db.QueryRowContext(ctx, getPelamarSaudaraKandungByID, idSaudara)
	var i PelamarSaudaraKandung
	err := row.Scan(
		&i.ID,
		&i.IDSaudara,
		&i.IDPelamar,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.PendidikanPekerjaan,
		&i.TglLahir,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPelamarSaudaraKandung = `-- name: ListPelamarSaudaraKandung :many
SELECT id, id_saudara, id_pelamar, nama, jenis_kelamin, tempat_lahir, pendidikan_pekerjaan, tgl_lahir, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_saudara_kandung
WHERE deleted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListPelamarSaudaraKandung(ctx context.Context) ([]PelamarSaudaraKandung, error) {
	rows, err := q.db.QueryContext(ctx, listPelamarSaudaraKandung)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PelamarSaudaraKandung
	for rows.Next() {
		var i PelamarSaudaraKandung
		if err := rows.Scan(
			&i.ID,
			&i.IDSaudara,
			&i.IDPelamar,
			&i.Nama,
			&i.JenisKelamin,
			&i.TempatLahir,
			&i.PendidikanPekerjaan,
			&i.TglLahir,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePelamarSaudaraKandung = `-- name: RestorePelamarSaudaraKandung :exec
UPDATE pelamar_saudara_kandung
SET deleted_at = NULL, deleted_by = NULL
WHERE id_saudara = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) RestorePelamarSaudaraKandung(ctx context.Context, idSaudara string) error {
	_, err := q.db.ExecContext(ctx, restorePelamarSaudaraKandung, idSaudara)
	return err
}

const softDeletePelamarSaudaraKandung = `-- name: SoftDeletePelamarSaudaraKandung :exec
UPDATE pelamar_saudara_kandung
SET deleted_at = NOW(), deleted_by = $1
WHERE id_saudara = $2 AND deleted_at IS NULL
`

type SoftDeletePelamarSaudaraKandungParams struct {
	DeletedBy sql.NullString `json:"deleted_by"`
	IDSaudara string         `json:"id_saudara"`
}

func (q *Queries) SoftDeletePelamarSaudaraKandung(ctx context.Context, arg SoftDeletePelamarSaudaraKandungParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePelamarSaudaraKandung, arg.DeletedBy, arg.IDSaudara)
	return err
}

const updatePelamarSaudaraKandung = `-- name: UpdatePelamarSaudaraKandung :one
UPDATE pelamar_saudara_kandung
SET
    nama = $1,
    jenis_kelamin = $2,
    tempat_lahir = $3,
    pendidikan_pekerjaan = $4,
    tgl_lahir = $5,
    updated_at = NOW(),
    updated_by = $6
WHERE id_saudara = $7 AND deleted_at IS NULL
    RETURNING id, id_saudara, id_pelamar, nama, jenis_kelamin, tempat_lahir, pendidikan_pekerjaan, tgl_lahir, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdatePelamarSaudaraKandungParams struct {
	Nama                string         `json:"nama"`
	JenisKelamin        interface{}    `json:"jenis_kelamin"`
	TempatLahir         sql.NullString `json:"tempat_lahir"`
	PendidikanPekerjaan sql.NullString `json:"pendidikan_pekerjaan"`
	TglLahir            sql.NullTime   `json:"tgl_lahir"`
	UpdatedBy           sql.NullString `json:"updated_by"`
	IDSaudara           string         `json:"id_saudara"`
}

func (q *Queries) UpdatePelamarSaudaraKandung(ctx context.Context, arg UpdatePelamarSaudaraKandungParams) (PelamarSaudaraKandung, error) {
	row := q.db.QueryRowContext(ctx, updatePelamarSaudaraKandung,
		arg.Nama,
		arg.JenisKelamin,
		arg.TempatLahir,
		arg.PendidikanPekerjaan,
		arg.TglLahir,
		arg.UpdatedBy,
		arg.IDSaudara,
	)
	var i PelamarSaudaraKandung
	err := row.Scan(
		&i.ID,
		&i.IDSaudara,
		&i.IDPelamar,
		&i.Nama,
		&i.JenisKelamin,
		&i.TempatLahir,
		&i.PendidikanPekerjaan,
		&i.TglLahir,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
