// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: pelamar_pendidikan_formal.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPelamarPendidikanFormal = `-- name: CreatePelamarPendidikanFormal :one
INSERT INTO pelamar_pendidikan_formal (
    id_pddk_formal, id_pelamar, jenjang_pddk, nama_sekolah, jurusan_fakultas, kota,
    tgl_lulus, ipk, created_at, created_by
) VALUES (
             $1, $2, $3, $4, $5, $6,
             $7, $8, (now() at time zone 'UTC')::TIMESTAMP, $9
         ) RETURNING id, id_pddk_formal, id_pelamar, jenjang_pddk, nama_sekolah, jurusan_fakultas, kota, tgl_lulus, ipk, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreatePelamarPendidikanFormalParams struct {
	IDPddkFormal    string          `json:"id_pddk_formal"`
	IDPelamar       string          `json:"id_pelamar"`
	JenjangPddk     string          `json:"jenjang_pddk"`
	NamaSekolah     string          `json:"nama_sekolah"`
	JurusanFakultas sql.NullString  `json:"jurusan_fakultas"`
	Kota            sql.NullString  `json:"kota"`
	TglLulus        sql.NullTime    `json:"tgl_lulus"`
	Ipk             sql.NullFloat64 `json:"ipk"`
	CreatedBy       string          `json:"created_by"`
}

func (q *Queries) CreatePelamarPendidikanFormal(ctx context.Context, arg CreatePelamarPendidikanFormalParams) (PelamarPendidikanFormal, error) {
	row := q.db.QueryRowContext(ctx, createPelamarPendidikanFormal,
		arg.IDPddkFormal,
		arg.IDPelamar,
		arg.JenjangPddk,
		arg.NamaSekolah,
		arg.JurusanFakultas,
		arg.Kota,
		arg.TglLulus,
		arg.Ipk,
		arg.CreatedBy,
	)
	var i PelamarPendidikanFormal
	err := row.Scan(
		&i.ID,
		&i.IDPddkFormal,
		&i.IDPelamar,
		&i.JenjangPddk,
		&i.NamaSekolah,
		&i.JurusanFakultas,
		&i.Kota,
		&i.TglLulus,
		&i.Ipk,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const getPelamarPendidikanFormalByID = `-- name: GetPelamarPendidikanFormalByID :one
SELECT id, id_pddk_formal, id_pelamar, jenjang_pddk, nama_sekolah, jurusan_fakultas, kota, tgl_lulus, ipk, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_pendidikan_formal
WHERE id_pddk_formal = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetPelamarPendidikanFormalByID(ctx context.Context, idPddkFormal string) (PelamarPendidikanFormal, error) {
	row := q.db.QueryRowContext(ctx, getPelamarPendidikanFormalByID, idPddkFormal)
	var i PelamarPendidikanFormal
	err := row.Scan(
		&i.ID,
		&i.IDPddkFormal,
		&i.IDPelamar,
		&i.JenjangPddk,
		&i.NamaSekolah,
		&i.JurusanFakultas,
		&i.Kota,
		&i.TglLulus,
		&i.Ipk,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listPelamarPendidikanFormal = `-- name: ListPelamarPendidikanFormal :many
SELECT id, id_pddk_formal, id_pelamar, jenjang_pddk, nama_sekolah, jurusan_fakultas, kota, tgl_lulus, ipk, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM pelamar_pendidikan_formal
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPelamarPendidikanFormal(ctx context.Context) ([]PelamarPendidikanFormal, error) {
	rows, err := q.db.QueryContext(ctx, listPelamarPendidikanFormal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PelamarPendidikanFormal
	for rows.Next() {
		var i PelamarPendidikanFormal
		if err := rows.Scan(
			&i.ID,
			&i.IDPddkFormal,
			&i.IDPelamar,
			&i.JenjangPddk,
			&i.NamaSekolah,
			&i.JurusanFakultas,
			&i.Kota,
			&i.TglLulus,
			&i.Ipk,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePelamarPendidikanFormal = `-- name: RestorePelamarPendidikanFormal :exec
UPDATE pelamar_pendidikan_formal
SET
    deleted_at = NULL,
    deleted_by = NULL
WHERE id_pddk_formal = $1
`

func (q *Queries) RestorePelamarPendidikanFormal(ctx context.Context, idPddkFormal string) error {
	_, err := q.db.ExecContext(ctx, restorePelamarPendidikanFormal, idPddkFormal)
	return err
}

const softDeletePelamarPendidikanFormal = `-- name: SoftDeletePelamarPendidikanFormal :exec
UPDATE pelamar_pendidikan_formal
SET
    deleted_at = (now() at time zone 'UTC')::TIMESTAMP,
    deleted_by = $1
WHERE id_pddk_formal = $2
  AND deleted_at IS NULL
`

type SoftDeletePelamarPendidikanFormalParams struct {
	DeletedBy    sql.NullString `json:"deleted_by"`
	IDPddkFormal string         `json:"id_pddk_formal"`
}

func (q *Queries) SoftDeletePelamarPendidikanFormal(ctx context.Context, arg SoftDeletePelamarPendidikanFormalParams) error {
	_, err := q.db.ExecContext(ctx, softDeletePelamarPendidikanFormal, arg.DeletedBy, arg.IDPddkFormal)
	return err
}

const updatePelamarPendidikanFormal = `-- name: UpdatePelamarPendidikanFormal :one
UPDATE pelamar_pendidikan_formal
SET
    jenjang_pddk = $1,
    nama_sekolah = $2,
    jurusan_fakultas = $3,
    kota = $4,
    tgl_lulus = $5,
    ipk = $6,
    updated_at = (now() at time zone 'UTC')::TIMESTAMP,
    updated_by = $7
WHERE id_pddk_formal = $8
  AND deleted_at IS NULL
    RETURNING id, id_pddk_formal, id_pelamar, jenjang_pddk, nama_sekolah, jurusan_fakultas, kota, tgl_lulus, ipk, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdatePelamarPendidikanFormalParams struct {
	JenjangPddk     string          `json:"jenjang_pddk"`
	NamaSekolah     string          `json:"nama_sekolah"`
	JurusanFakultas sql.NullString  `json:"jurusan_fakultas"`
	Kota            sql.NullString  `json:"kota"`
	TglLulus        sql.NullTime    `json:"tgl_lulus"`
	Ipk             sql.NullFloat64 `json:"ipk"`
	UpdatedBy       sql.NullString  `json:"updated_by"`
	IDPddkFormal    string          `json:"id_pddk_formal"`
}

func (q *Queries) UpdatePelamarPendidikanFormal(ctx context.Context, arg UpdatePelamarPendidikanFormalParams) (PelamarPendidikanFormal, error) {
	row := q.db.QueryRowContext(ctx, updatePelamarPendidikanFormal,
		arg.JenjangPddk,
		arg.NamaSekolah,
		arg.JurusanFakultas,
		arg.Kota,
		arg.TglLulus,
		arg.Ipk,
		arg.UpdatedBy,
		arg.IDPddkFormal,
	)
	var i PelamarPendidikanFormal
	err := row.Scan(
		&i.ID,
		&i.IDPddkFormal,
		&i.IDPelamar,
		&i.JenjangPddk,
		&i.NamaSekolah,
		&i.JurusanFakultas,
		&i.Kota,
		&i.TglLulus,
		&i.Ipk,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
